arch:
  - amd64
  - ppc64le
sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - node
  - '15'
  - '14'
  - '13'
  - '0.12'
  - '0.10'
jobs:
  exclude:
     - node_js: '0.12'
       arch: ppc64le
     - node_js: '0.10'
       arch: ppc64le
